name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: GoReleaser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Test
        run: go test ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7.2.1
        with:
          distribution: goreleaser
          version: v2.16.0
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
